### ISSUE TITLE
ensureDir is not a function

### ISSUE THREAD

**Issue by danielo515** [st-one-io/node-red-contrib-smb#11]
I tried to ensure that a folder exists, but I get an error saying that self.ensureDir is not a function. 

```
"TypeError: self.smbClient.ensureDir is not a function"
```

**Comment by UNOPARATOR** [comment]
Same here...

> TypeError: self.smbClient.ensureDir is not a function
    at SmbConfig.ensureDir (/home/username/.node-red/node_modules/node-red-contrib-smb/red/smb.js:190:44)
    at onNewMsg (/home/username/.node-red/node_modules/node-red-contrib-smb/red/smb.js:432:33)
    at SmbFunction._inputCallback (/home/azureuser/.node-red/node_modules/node-red-contrib-smb/red/smb.js:27:9)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:149:13)
    at SmbFunction.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at SmbFunction.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at SmbFunction.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:478:10)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modu...

**Comment by danielo515** [comment]
Will you be open to accept a PR?

**Comment by gfcittolin** [comment]
Sure @danielo515, right now I'm a bit overwhelmed by other tasks, so I'm not able to work on a fix for this. But I'll gladly accept a PR for that
